import { existsSync } from "node:fs";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { singularize, snake, titleCase } from "./strings.js";

/** Field types the generator can scaffold without extra schema imports. */
const SUPPORTED_TYPES = [
  "text",
  "textarea",
  "email",
  "date",
  "datetime",
] as const;
type FieldType = (typeof SUPPORTED_TYPES)[number];

export interface FieldSpec {
  name: string;
  type: FieldType;
  required: boolean;
}

export interface GenerateOptions {
  /** Entity/table/route id, e.g. "assets" (plural, lowercase). */
  name: string;
  fields: FieldSpec[];
  label?: string;
  singular?: string;
  /** Repo root (defaults to cwd). */
  root: string;
}

const MARKERS = {
  tables: "// @power-app/cli:tables",
  imports: "// @power-app/cli:imports",
  register: "// @power-app/cli:register",
};

export function parseFieldSpec(raw: string | undefined): FieldSpec[] {
  if (!raw) {
    return [
      { name: "title", type: "text", required: true },
      { name: "description", type: "textarea", required: false },
    ];
  }
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((part) => {
      const [name, type = "text", flag] = part.split(":").map((p) => p.trim());
      if (!name || !/^[a-zA-Z][a-zA-Z0-9]*$/.test(name)) {
        throw new Error(`Invalid field name "${name}".`);
      }
      if (!SUPPORTED_TYPES.includes(type as FieldType)) {
        throw new Error(
          `Unsupported field type "${type}" for "${name}". Supported: ${SUPPORTED_TYPES.join(", ")}. (Add select/number/boolean fields by hand.)`,
        );
      }
      return { name, type: type as FieldType, required: flag === "required" };
    });
}

// ── code fragments ───────────────────────────────────────────────────────────

function zodField({ name, type, required }: FieldSpec): string {
  let expr: string;
  switch (type) {
    case "email":
      expr = "z.string().email()";
      break;
    case "date":
    case "datetime":
      expr = "z.string()";
      break;
    default:
      expr = "z.string().trim().max(2000)";
  }
  if (!required) expr += ".optional().nullable()";
  return `  ${name}: ${expr},`;
}

function fieldMeta({ name, type, required }: FieldSpec): string {
  const label = titleCase(name);
  const req = required ? "required: true, " : "";
  return `    { name: "${name}", label: "${label}", type: "${type}", ${req}showInTable: true },`;
}

function drizzleColumn({ name, type, required }: FieldSpec): string {
  const col = snake(name);
  const base =
    type === "date" || type === "datetime"
      ? `timestamp("${col}", { withTimezone: true })`
      : `text("${col}")`;
  return `  ${name}: ${base}${required ? ".notNull()" : ""},`;
}

function sqlColumn({ name, type, required }: FieldSpec): string {
  const col = snake(name);
  const t = type === "date" || type === "datetime" ? "timestamptz" : "text";
  return `  ${col} ${t}${required ? " NOT NULL" : ""},`;
}

// ── file builders ──────────────────────────────────────────────────────────

function entityFile(opts: GenerateOptions): string {
  const { name, fields } = opts;
  const label = opts.label ?? titleCase(name);
  const labelSingular = opts.singular ?? singularize(titleCase(name));
  return `import { z } from "zod";
import { defineEntity } from "@power-app/core";
import { ${name} } from "../db/schema.js";

const createSchema = z.object({
${fields.map(zodField).join("\n")}
});

const updateSchema = createSchema.partial();

export const ${name}Entity = defineEntity({
  name: "${name}",
  label: "${label}",
  labelSingular: "${labelSingular}",
  table: ${name},
  createSchema,
  updateSchema,
  defaultSort: { field: "createdAt", dir: "desc" },
  fields: [
${fields.map(fieldMeta).join("\n")}
    { name: "createdBy", label: "Created By", type: "text", readOnly: true, showInTable: true },
    { name: "createdAt", label: "Created", type: "datetime", readOnly: true, showInTable: true },
  ],
  access: {
    list: "*",
    read: "*",
    create: ["admin", "editor"],
    update: ["admin", "editor"],
    delete: ["admin"],
  },
});
`;
}

function tableBlock(opts: GenerateOptions): string {
  const { name, fields } = opts;
  return `export const ${name} = pgTable("${name}", {
  id: uuid("id").primaryKey().defaultRandom(),
${fields.map(drizzleColumn).join("\n")}
  createdBy: text("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
`;
}

function migrationSql(opts: GenerateOptions): string {
  const { name, fields } = opts;
  return `-- Table for the "${name}" entity (generated by \`paf new entity\`).
CREATE TABLE IF NOT EXISTS ${name} (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
${fields.map(sqlColumn).join("\n")}
  created_by  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
`;
}

// ── helpers ──────────────────────────────────────────────────────────────────

function insertBefore(content: string, marker: string, fragment: string): string {
  const idx = content.indexOf(marker);
  if (idx === -1) throw new Error(`Marker not found: ${marker}`);
  // Insert at the start of the marker's line.
  const lineStart = content.lastIndexOf("\n", idx) + 1;
  return content.slice(0, lineStart) + fragment + content.slice(lineStart);
}

async function nextMigrationNumber(dir: string): Promise<string> {
  const files = await readdir(dir);
  let max = 0;
  for (const f of files) {
    const m = /^(\d+)_/.exec(f);
    if (m && m[1]) max = Math.max(max, Number(m[1]));
  }
  return String(max + 1).padStart(4, "0");
}

export interface GenerateResult {
  created: string[];
  modified: string[];
}

/** Generates and wires up a new entity. Throws on any conflict. */
export async function generateEntity(
  opts: GenerateOptions,
): Promise<GenerateResult> {
  const { name, root } = opts;
  if (!/^[a-z][a-z0-9_]*$/.test(name)) {
    throw new Error(
      `Entity name "${name}" must be lowercase letters/numbers/underscores (use the plural, e.g. "assets").`,
    );
  }

  const serverDir = path.join(root, "apps/server");
  const schemaPath = path.join(serverDir, "src/db/schema.ts");
  const registryPath = path.join(serverDir, "src/entities/index.ts");
  const entityPath = path.join(serverDir, `src/entities/${name}.ts`);
  const migrationsDir = path.join(serverDir, "migrations");

  if (!existsSync(schemaPath) || !existsSync(registryPath)) {
    throw new Error(
      `Could not find apps/server sources under "${root}". Run paf from the repo root (or pass --root).`,
    );
  }
  if (existsSync(entityPath)) {
    throw new Error(`Entity already exists: ${path.relative(root, entityPath)}`);
  }

  const created: string[] = [];
  const modified: string[] = [];

  // 1. entity definition file
  await writeFile(entityPath, entityFile(opts), "utf8");
  created.push(path.relative(root, entityPath));

  // 2. migration
  const num = await nextMigrationNumber(migrationsDir);
  const migrationPath = path.join(migrationsDir, `${num}_${name}.sql`);
  await writeFile(migrationPath, migrationSql(opts), "utf8");
  created.push(path.relative(root, migrationPath));

  // 3. drizzle table → schema.ts
  let schema = await readFile(schemaPath, "utf8");
  schema = insertBefore(schema, MARKERS.tables, tableBlock(opts) + "\n");
  await writeFile(schemaPath, schema, "utf8");
  modified.push(path.relative(root, schemaPath));

  // 4. register in entities/index.ts (import + array entry)
  let registry = await readFile(registryPath, "utf8");
  registry = insertBefore(
    registry,
    MARKERS.imports,
    `import { ${name}Entity } from "./${name}.js";\n`,
  );
  registry = insertBefore(registry, MARKERS.register, `  ${name}Entity,\n`);
  await writeFile(registryPath, registry, "utf8");
  modified.push(path.relative(root, registryPath));

  return { created, modified };
}
